import Card from "@/components/card";
import Header from "@/components/header";
import Head from "next/head";
import React, { useState } from "react";
import CardsData from "./api/JsonCardsData";

export default function Home() {
  //cards state
  const [cards, setCards] = useState(allCardsdata);

  const pool_1 = cards.filter((c) => c.source_slug === "pool-1");
  const pool_2 = cards.filter((c) => c.source_slug === "pool-2");
  const pool_3 = cards.filter((c) => c.source_slug === "pool-3");
  const pool_4 = cards.filter((c) => c.source_slug === "pool-4");
  const pool_5 = cards.filter((c) => c.source_slug === "pool-5");
  const starter = cards.filter((c) => c.source_slug === "starter-card");

  //function to change collected prop
  function toggle(cid) {
    setCards((prevCards) => {
      return prevCards.map((card) => {
        return card.cid === cid
          ? { ...card, collected: !card.collected }
          : card;
      });
    });
  }

  return (
    <div className=" bg-slate-800 min-w-full min-h-screen flex flex-col justify-center items-center">
      <Header></Header>
      <Head>
        <title>Marvel Snap Deckbuilder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="collection-containner w-3/4 ">
        <h2 className="text-white text-4xl font-extrabold m-4 pl-12">
          Starter Cards
        </h2>
        <div className="cardContainer flex flex-wrap place-content-start  h-full w-full pl-10">
          {starter.map((c) => (
            <Card props={c} key={c.cid} toggle={toggle}></Card>
          ))}
        </div>

        <h2 className="text-white text-4xl font-extrabold m-4 pl-12">
          Pool 1 Cards
        </h2>
        <div className="cardContainer flex flex-wrap place-content-start  h-full w-full pl-10">
          {pool_1.map((c) => (
            <>
              <Card props={c} key={c.cid} toggle={toggle}></Card>
            </>
          ))}
        </div>
        <h2 className="text-white text-4xl font-extrabold m-4 pl-12">
          Pool 2 Cards
        </h2>
        <div className="cardContainer flex flex-wrap place-content-start  h-full w-full pl-10">
          {pool_2.map((c) => (
            <>
              <Card props={c} key={c.cid} toggle={toggle}></Card>
            </>
          ))}
        </div>

        <h2 className="text-white text-4xl font-extrabold m-5 pl-12">
          Pool 3 Cards
        </h2>

        <div className="cardContainer flex flex-wrap place-content-start  h-full w-full pl-10">
          {pool_3.map((c) => (
            <>
              <Card props={c} key={c.cid} toggle={toggle}></Card>
            </>
          ))}
        </div>

        <h2 className="text-white text-4xl font-extrabold m-5 pl-12">
          Pool 4 Cards
        </h2>

        <div className="cardContainer flex flex-wrap place-content-start  h-full w-full pl-10">
          {pool_4.map((c) => (
            <>
              <Card props={c} key={c.cid} toggle={toggle}></Card>
            </>
          ))}
        </div>

        <h2 className="text-white text-4xl font-extrabold m-5 pl-12">
          Pool 5 Cards
        </h2>
        <div className="cardContainer flex flex-wrap place-content-start  h-full w-full pl-10">
          {pool_5.map((c) => (
            <>
              <Card props={c} key={c.cid} toggle={toggle}></Card>
            </>
          ))}
        </div>
      </div>
    </div>
  );
}

//cread filtered list
const allCardsdata = CardsData.filter((c) => c.type === "Character").map(
  (c) => {
    return { ...c, collected: false };
  }
);
